name: CI

on:
  workflow_dispatch:
    inputs:
      # Specify a source branch to pull the code from
      source_ref:
        description: 'The source branch or ref to build from'
        default: 'master'
        required: true

      # Docker image tag: windowsservercore-ltsc2025-qt6.10-64bit-1
      # Using digest for easier verification of the transparent build chain.
      # https://github.com/LibrePCB/docker-librepcb-dev/actions/runs/20745227440/job/59560845499
      builder_digest:
        description: 'The docker image digest to use for building LibrePCB'
        default: 'sha256:f78cc56d8c863317e44d20ab5a14080e20c0f13af8cab20533d2a6437a2437c9'
        required: true

env:
  # Specify build author as an environment variable because on Apple Silicon
  # build_librepcb.sh is run locally where we want to use a different author.
  LIBREPCB_BUILD_AUTHOR: "LibrePCB CI"

  # Configure ccache.
  CCACHE_MAXSIZE: 1G

  # Incremental builds make no sense on CI -> disable it to avoid creating
  # additional build artifacts.
  CARGO_INCREMENTAL: 0

permissions:
  contents: write

jobs:
  macos-arm64:
    name: MacOS ARM64
    # Make sure the 'runs-on' really refers to an Apple Silicon CPU:
    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
    runs-on: macos-14
    environment: OSSign
    env:
      OS: 'mac'
      ARCH: 'arm64'
      COPYFILE_DISABLE: 1 # https://superuser.com/questions/259703/get-mac-tar-to-stop-putting-filenames-in-tar-archives
      HOMEBREW_NO_INSTALL_CLEANUP: 1 # Might speed up homebrew commands
      CCACHE_DIR: '/Users/runner/ccache-dir'
      CARGO_HOME: '/Users/runner/cargo-home'
      # Qt 6.7.3 is the last version that runs on macOS 11.
      QT_URL: 'https://qt.mirror.constant.com/archive/qt/6.7/6.7.3/single/qt-everywhere-src-6.7.3.tar.xz'
      QT_SHA256: 'a3f1d257cbb14c6536585ffccf7c203ce7017418e1a0c2ed7c316c20c729c801'
      QT_ROOT: '/Users/runner/qt'
      OCC_VERSION: '7_9_1'
      OCC_ROOT: '/Users/runner/occ'
      MACOSX_DEPLOYMENT_TARGET: '11'  # Picked up by CMake and Rust
      CMAKE_PREFIX_PATH: '/Users/runner/qt/lib/cmake/Qt6:/Users/runner/occ/lib/cmake/opencascade'
    steps:
      - name: Info
        run: |
            echo "Running on: ${{ runner.os }} ( ${{ runner.name }} )"
            echo "LibrePCB source ref: ${{ github.event.inputs.source_ref }}"
            echo "Build author: ${{ env.LIBREPCB_BUILD_AUTHOR }}"

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: 'LibrePCB/LibrePCB'
          ref: ${{ github.event.inputs.source_ref }}

      - name: Print Environment
        run: ./ci/print_environment.sh
      # caching --->

      - name: Cache .ccache
        uses: actions/cache@v4
        with:
          key: ${{ github.job }}-${{ github.ref }}
          restore-keys: ${{ github.job }}-refs/heads/master
          path: ${{ env.CCACHE_DIR }}

      - name: Cache .cargo
        uses: actions/cache@v4
        with:
          key: ${{ github.job }}-${{ hashFiles('libs/librepcb/**/Cargo.lock') }}-${{ github.ref }}
          restore-keys: ${{ github.job }}-${{ hashFiles('libs/librepcb/**/Cargo.lock') }}-refs/heads/master
          path: |
            ${{ env.CARGO_HOME }}/bin/
            ${{ env.CARGO_HOME }}/registry/index/
            ${{ env.CARGO_HOME }}/registry/cache/
            ${{ env.CARGO_HOME }}/git/db/
            ./build/cargo/
            ./libs/librepcb/rust-core/target/

      - name: Cache Qt
        uses: actions/cache@v4
        with:
          key: qt-${{ env.QT_SHA256 }}-macos-${{ env.MACOSX_DEPLOYMENT_TARGET }}-v6
          path: ${{ env.QT_ROOT }}

      - name: Cache OpenCascade
        uses: actions/cache@v4
        with:
          key: occ-${{ env.OCC_VERSION }}-macos-${{ env.MACOSX_DEPLOYMENT_TARGET }}-v6
          path: ${{ env.OCC_ROOT }}

      # <--- caching
      - name: Install Dependencies
        run: |
          source ./ci/install_dependencies.sh
          # Pass modified PATH to following steps:
          echo "$PATH" > "$GITHUB_PATH"

      - name: Print New Environment
        run: ./ci/print_environment.sh

      - name: Build LibrePCB
        run: ./ci/build_librepcb.sh

      - name: Build Bundle
        run: ./ci/build_mac_bundle.sh

      - name: Install App Store Connect API Key
        run: |
             mkdir -p private_keys/
             echo '${{ secrets.MACOS_NOTARY_JSON }}' > private_keys/macos_notary.json
             echo '${{ secrets.MACOS_SIGN_PEM }}' > private_keys/macos.pem

      - name: Sign App
        uses: indygreg/apple-code-sign-action@v1
        with:
             input_path: build/install/LibrePCB.app
             pem_file: private_keys/macos.pem
             app_store_connect_api_key_json_file: private_keys/macos_notary.json

      - name: Build DMG
        run: ./ci/build_mac_dmg.sh

      - name: Sign and Notarize
        uses: indygreg/apple-code-sign-action@v1
        with:
             input_path: artifacts/nightly_builds/librepcb-nightly-mac-${{ env.ARCH }}.dmg
             notarize: true
             staple: true
             pem_file: private_keys/macos.pem
             app_store_connect_api_key_json_file: private_keys/macos_notary.json

      - name: Tar Artifacts
        run: ./ci/tar_artifacts.sh

      - name: Upload Signed Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}
          path: artifacts/artifacts.tar
