name: CI

on:
  workflow_dispatch:
    inputs:
      # Specify a source branch to pull the code from
      source_ref:
        description: 'The source branch or ref to build from'
        default: 'master'
        required: true

      # Docker image tag: windowsservercore-ltsc2025-qt6.10-64bit-1
      # Using digest for easier verification of the transparent build chain.
      # https://github.com/LibrePCB/docker-librepcb-dev/actions/runs/20745227440/job/59560845499
      builder_digest:
        description: 'The docker image digest to use for building LibrePCB'
        default: 'sha256:f78cc56d8c863317e44d20ab5a14080e20c0f13af8cab20533d2a6437a2437c9'
        required: true

env:
  # Specify build author as an environment variable because on Apple Silicon
  # build_librepcb.sh is run locally where we want to use a different author.
  LIBREPCB_BUILD_AUTHOR: "LibrePCB CI"

  # Configure ccache.
  CCACHE_MAXSIZE: 1G

  # Incremental builds make no sense on CI -> disable it to avoid creating
  # additional build artifacts.
  CARGO_INCREMENTAL: 0

permissions:
  contents: write

jobs:
  windows-x64:
    name: Windows x86_64
    runs-on: windows-2025
    environment: OSSign
    steps:
      - name: Info
        run: |
            echo "Running on: ${{ runner.os }} ( ${{ runner.name }} )"
            echo "LibrePCB source ref: ${{ github.event.inputs.source_ref }}"
            echo "Docker image digest: ${{ github.event.inputs.builder_digest }}"
            echo "Build author: ${{ env.LIBREPCB_BUILD_AUTHOR }}"

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: 'LibrePCB/LibrePCB'
          ref: ${{ github.event.inputs.source_ref }}

      - name: Start Docker Container
        run: >
          docker run -d -t --name ci -w C:/work
          -v ${{ github.workspace }}:C:/work
          -e OS="windows"
          -e ARCH="x86_64"
          -e CI_BRANCH_NAME="${{ github.event.inputs.source_ref }}"
          -e CCACHE_DIR="C:/work/build/.ccache-dir"
          -e CCACHE_MAXSIZE="${{ env.CCACHE_MAXSIZE }}"
          -e CARGO_HOME="C:/work/build/.cargo-home"
          -e CARGO_INCREMENTAL="${{ env.CARGO_INCREMENTAL }}"
          -e LIBREPCB_BUILD_AUTHOR="${{ env.LIBREPCB_BUILD_AUTHOR }}"
          "ghcr.io/librepcb/docker-librepcb-dev@${{ github.event.inputs.builder_digest }}"

      - name: Print Environment
        run: docker exec ci bash ./ci/print_environment.sh

      - name: Install Dependencies
        run: docker exec ci bash ./ci/install_dependencies.sh
      # caching --->

      - name: Cache .ccache
        uses: actions/cache@v4
        with:
          key: ${{ github.job }}-${{ github.ref }}
          restore-keys: ${{ github.job }}-refs/heads/master
          path: build/.ccache-dir

      - name: Cache .cargo
        uses: actions/cache@v4
        with:
          key: ${{ github.job }}-${{ hashFiles('libs/librepcb/**/Cargo.lock') }}-${{ github.ref }}
          restore-keys: ${{ github.job }}-${{ hashFiles('libs/librepcb/**/Cargo.lock') }}-refs/heads/master
          path: |
            ./build/.cargo-home/bin/
            ./build/.cargo-home/registry/index/
            ./build/.cargo-home/registry/cache/
            ./build/.cargo-home/git/db/
            ./build/cargo/
            ./libs/librepcb/rust-core/target/

      # <--- caching
      - name: Print New Environment  # Print again since it has been modified
        run: docker exec ci bash ./ci/print_environment.sh

      - name: Build LibrePCB
        run: docker exec ci bash ./ci/build_librepcb.sh

      - name: Build Archive
        run: >
          docker exec
          -e AST_CERT="${{ secrets.AST_CERT }}"
          -e AST_IDENT="${{ secrets.AST_IDENT }}"
          -e AST_SECRET="${{ secrets.AST_SECRET }}"
          -e AST_TD="${{ secrets.AST_TD }}"
          -e AST_TENANT="${{ secrets.AST_TENANT }}"
          -e AST_TIMESTAMP="${{ secrets.AST_TIMESTAMP }}"
          -e AST_VAULT="${{ secrets.AST_VAULT }}"
          ci bash ./ci/build_windows_archive.sh

      - name: Build Installer
        run: >
          docker exec
          -e AST_CERT="${{ secrets.AST_CERT }}"
          -e AST_IDENT="${{ secrets.AST_IDENT }}"
          -e AST_SECRET="${{ secrets.AST_SECRET }}"
          -e AST_TD="${{ secrets.AST_TD }}"
          -e AST_TENANT="${{ secrets.AST_TENANT }}"
          -e AST_TIMESTAMP="${{ secrets.AST_TIMESTAMP }}"
          -e AST_VAULT="${{ secrets.AST_VAULT }}"
          ci bash ./ci/build_windows_installer.sh

      - name: Tar Artifacts
        run: docker exec ci bash ./ci/tar_artifacts.sh

      - name: Upload Signed Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}
          path: artifacts/artifacts.tar
